name: expat
version: 0.1.0
description: >-
  Dart FFI bindings to a stream-oriented XML parser library written in C.
homepage: https://libexpat.github.io/
repository: https://github.com/jpnurmi/dart_expat
issue_tracker: https://github.com/jpnurmi/dart_expat/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
  meta: ^1.2.3

dev_dependencies:
  ffigen: ^1.0.6
  pedantic: ^1.9.0
  test: ^1.14.4
